"""migration: summary-userid

Revision ID: 5cd3522f2d40
Revises: 58db06d7bdf3
Create Date: 2025-08-07 16:16:44.051190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd3522f2d40'
down_revision: Union[str, Sequence[str], None] = '58db06d7bdf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('owner_id', sa.String(length=26), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'owner_id')
    # ### end Alembic commands ###
