"""follow

Revision ID: 58db06d7bdf3
Revises: dbee70730d60
Create Date: 2025-08-07 15:36:09.900511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58db06d7bdf3'
down_revision: Union[str, Sequence[str], None] = 'dbee70730d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('follower_id', sa.String(length=26), nullable=False),
    sa.Column('followee_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followee_id', name='unique_follow_relation')
    )
    op.create_index('idx_follow_created_at', 'follows', ['created_at'], unique=False)
    op.create_index('idx_follow_followee', 'follows', ['followee_id'], unique=False)
    op.create_index('idx_follow_followee_created', 'follows', ['followee_id', 'created_at'], unique=False)
    op.create_index('idx_follow_follower', 'follows', ['follower_id'], unique=False)
    op.create_index('idx_follow_follower_created', 'follows', ['follower_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_follow_follower_created', table_name='follows')
    op.drop_index('idx_follow_follower', table_name='follows')
    op.drop_index('idx_follow_followee_created', table_name='follows')
    op.drop_index('idx_follow_followee', table_name='follows')
    op.drop_index('idx_follow_created_at', table_name='follows')
    op.drop_table('follows')
    # ### end Alembic commands ###
