"""Add social tables (likes, comments, bookmarks, follows)

Revision ID: 00e9aef3b1f5
Revises: df3139545345
Create Date: 2025-08-11 03:39:43.876589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e9aef3b1f5'
down_revision: Union[str, Sequence[str], None] = 'df3139545345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
