"""week title

Revision ID: df3139545345
Revises: 5cd3522f2d40
Create Date: 2025-08-10 09:56:07.880277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3139545345'
down_revision: Union[str, Sequence[str], None] = '5cd3522f2d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_schedules', sa.Column('title', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('week_schedules', 'title')
    # ### end Alembic commands ###
