global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['app:8000']  # FastAPI 애플리케이션 메트릭 엔드포인트
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'fastapi-metrics-server'
    static_configs:
      - targets: ['app:8001']  # Prometheus 클라이언트 서버
    scrape_interval: 5s
    metrics_path: /
