import app.modules.user.infrastructure.db_model.user  # type: ignore  # noqa: F401
import app.modules.curriculum.infrastructure.db_model.curriculum  # type: ignore  # noqa: F401
import app.modules.curriculum.infrastructure.db_model.week_schedule  # type: ignore  # noqa: F401
import app.modules.learning.infrastructure.db_model.summary  # type: ignore  # noqa: F401
import app.modules.learning.infrastructure.db_model.feedback  # type: ignore  # noqa: F401
import app.modules.taxonomy.infrastructure.db_model.tag  # type: ignore  # noqa: F401
import app.modules.taxonomy.infrastructure.db_model.category  # type: ignore  # noqa: F401
import app.modules.taxonomy.infrastructure.db_model.curriculum_tag  # type: ignore  # noqa: F401
import app.modules.social.infrastructure.db_model.like  # type: ignore  # noqa: F401
import app.modules.social.infrastructure.db_model.comment  # type: ignore  # noqa: F401
import app.modules.social.infrastructure.db_model.bookmark  # type: ignore  # noqa: F401
import app.modules.social.infrastructure.db_model.follow  # type: ignore  # noqa: F401
